name: dart_openai_sdk
description: A Flutter/Dart SDK for OpenAI API by LitaVar.
version: 6.0.0
homepage: https://github.com/LiteVar/dart_openai_sdk
repository: https://github.com/LiteVar/dart_openai_sdk
documentation: https://github.com/LiteVar/dart_openai_sdk/blob/main/README.md
issue_tracker: https://github.com/LiteVar/dart_openai_sdk/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  collection: ^1.17.2
  fetch_client: ^1.0.2
  ovo: ^0.0.2
  web_socket_channel: ^3.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.3
